adminUser:
  password: vault:pr-115-6-gke-upgrade/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:pr-115-6-gke-upgrade/pipelineUser:token
  username: cjxd-bot-test
prow:
  hmacToken: vault:pr-115-6-gke-upgrade/prow:hmacToken
